import { Inter } from 'next/font/google';  // Make sure it's being imported like this
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  weight: '400',  // You can adjust weight as needed
});

export const metadata = {
  title: 'Sveto',
  description: 'Generated by create.xyz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}